version: "3"
services:
    sales-server:
        networks:
            - default
        restart: always 
        image: axmouth/sales-report-demo-server:latest
        container_name: sales-report-demo-server
        ports:
        - "3100:3100"
        - "4000:4000"
        environment:
        - MONGODOCKER_URI=mongodb://localhost:27017/sales-report-demo
        deploy:
            restart_policy:
                condition: any 
    sales-client:
        restart: always 
        image: axmouth/sales-report-demo-client:latest
        container_name: sales-report-demo-client
        ports:
            - "4201:80"
        deploy:
            restart_policy:
                condition: any 